(* The error-resilient parser of Jasmin, with Mastic.

   [strict] is the normal path of Jasmin (the parser generated by Menhir,
   the lexer raises on errors); [resilient] never fails: it returns the
   errors, the tokens inserted by the recovery and an AST with error nodes. *)

open Syntax
module I = Parser.MenhirInterpreter

(* the normal path, as Jasmin's Parseio.parse_program *)
let strict lexbuf = Parser.module_ Lexer.main lexbuf

(* the text being parsed, to know where lines begin and to keep the text of
   the tokens folded into an error *)
let text = ref ""

(* the baseline strategy of section 9 of the README (JAZZ_BASELINE set) *)
let baseline = Sys.getenv_opt "JAZZ_BASELINE" <> None

module ProgramParser = struct
  type ast = pprogram
  type 'a checkpoint = 'a I.checkpoint
  let main = Parser.Incremental.module_
  type token = Parser.token
  let token = Lexer.main
end

module Recovery = struct
  type token = Parser.token
  let show_token _ = ""
  type 'a symbol = 'a I.symbol
  type xsymbol = I.xsymbol
  type 'a terminal = 'a I.terminal
  type 'a env = 'a I.env
  type production = I.production

  (* the names of the symbols, for debugging (MASTIC_DEBUG) *)
  let name_of_symbol : type a. a symbol -> string = function
    | I.T I.T_ALIGNED -> "ALIGNED"
    | I.T I.T_AMP -> "AMP"
    | I.T I.T_AMPAMP -> "AMPAMP"
    | I.T I.T_ARRAYINIT -> "ARRAYINIT"
    | I.T I.T_ASSERT -> "ASSERT"
    | I.T I.T_BANG -> "BANG"
    | I.T I.T_BANGEQ -> "BANGEQ"
    | I.T I.T_COLON -> "COLON"
    | I.T I.T_COLONCOLON -> "COLONCOLON"
    | I.T I.T_COMMA -> "COMMA"
    | I.T I.T_CONSTANT -> "CONSTANT"
    | I.T I.T_DOT -> "DOT"
    | I.T I.T_DOWNTO -> "DOWNTO"
    | I.T I.T_ELSE -> "ELSE"
    | I.T I.T_EOF -> "EOF"
    | I.T I.T_EQ -> "EQ"
    | I.T I.T_EQEQ -> "EQEQ"
    | I.T I.T_ERROR_TOKEN -> "ERROR_TOKEN"
    | I.T I.T_EXEC -> "EXEC"
    | I.T I.T_EXPORT -> "EXPORT"
    | I.T I.T_FALSE -> "FALSE"
    | I.T I.T_FN -> "FN"
    | I.T I.T_FOR -> "FOR"
    | I.T I.T_FROM -> "FROM"
    | I.T I.T_GE -> "GE"
    | I.T I.T_GLOBAL -> "GLOBAL"
    | I.T I.T_GT -> "GT"
    | I.T I.T_GTGT -> "GTGT"
    | I.T I.T_HAT -> "HAT"
    | I.T I.T_IF -> "IF"
    | I.T I.T_INLINE -> "INLINE"
    | I.T I.T_INSTR_ERROR_TOKEN -> "INSTR_ERROR_TOKEN"
    | I.T I.T_INT -> "INT"
    | I.T I.T_ITEM_ERROR_TOKEN -> "ITEM_ERROR_TOKEN"
    | I.T I.T_LBRACE -> "LBRACE"
    | I.T I.T_LBRACKET -> "LBRACKET"
    | I.T I.T_LE -> "LE"
    | I.T I.T_LPAREN -> "LPAREN"
    | I.T I.T_LT -> "LT"
    | I.T I.T_LTLT -> "LTLT"
    | I.T I.T_MINUS -> "MINUS"
    | I.T I.T_MUTABLE -> "MUTABLE"
    | I.T I.T_NAMESPACE -> "NAMESPACE"
    | I.T I.T_NID -> "NID"
    | I.T I.T_PARAM -> "PARAM"
    | I.T I.T_PERCENT -> "PERCENT"
    | I.T I.T_PIPE -> "PIPE"
    | I.T I.T_PIPEPIPE -> "PIPEPIPE"
    | I.T I.T_PLUS -> "PLUS"
    | I.T I.T_POINTER -> "POINTER"
    | I.T I.T_QUESTIONMARK -> "QUESTIONMARK"
    | I.T I.T_RARROW -> "RARROW"
    | I.T I.T_RBRACE -> "RBRACE"
    | I.T I.T_RBRACKET -> "RBRACKET"
    | I.T I.T_REG -> "REG"
    | I.T I.T_REQUIRE -> "REQUIRE"
    | I.T I.T_RETURN -> "RETURN"
    | I.T I.T_ROL -> "ROL"
    | I.T I.T_ROR -> "ROR"
    | I.T I.T_RPAREN -> "RPAREN"
    | I.T I.T_SEMICOLON -> "SEMICOLON"
    | I.T I.T_SHARP -> "SHARP"
    | I.T I.T_SHARPLBRACKET -> "SHARPLBRACKET"
    | I.T I.T_SLASH -> "SLASH"
    | I.T I.T_STACK -> "STACK"
    | I.T I.T_STAR -> "STAR"
    | I.T I.T_STRING -> "STRING"
    | I.T I.T_SVSIZE -> "SVSIZE"
    | I.T I.T_SWSIZE -> "SWSIZE"
    | I.T I.T_TO -> "TO"
    | I.T I.T_TRUE -> "TRUE"
    | I.T I.T_TYPE -> "TYPE"
    | I.T I.T_T_BOOL -> "T_BOOL"
    | I.T I.T_T_INT -> "T_INT"
    | I.T I.T_T_INT_CAST -> "T_INT_CAST"
    | I.T I.T_T_W -> "T_W"
    | I.T I.T_UNALIGNED -> "UNALIGNED"
    | I.T I.T_UNDERSCORE -> "UNDERSCORE"
    | I.T I.T_WHILE -> "WHILE"
    | I.T I.T_error -> "error"
    | I.N I.N_annot_pparamdecl -> "annot_pparamdecl"
    | I.N I.N_annot_stor_type -> "annot_stor_type"
    | I.N I.N_annotation -> "annotation"
    | I.N I.N_annotationlabel -> "annotationlabel"
    | I.N I.N_annotations -> "annotations"
    | I.N I.N_arr_access -> "arr_access"
    | I.N I.N_arr_access_i -> "arr_access_i"
    | I.N I.N_arr_access_len -> "arr_access_len"
    | I.N I.N_attribute -> "attribute"
    | I.N I.N_call_conv -> "call_conv"
    | I.N I.N_cast -> "cast"
    | I.N I.N_castop -> "castop"
    | I.N I.N_castop1 -> "castop1"
    | I.N I.N_from -> "from"
    | I.N I.N_implicites -> "implicites"
    | I.N I.N_keyword -> "keyword"
    | I.N I.N_list_loc_top__ -> "list_loc_top__"
    | I.N I.N_list_pinstr_ -> "list_pinstr_"
    | I.N I.N_list_top_annotation_ -> "list_top_annotation_"
    | I.N I.N_loption_separated_nonempty_list_COMMA_annot_pparamdecl__ -> "loption_separated_nonempty_list_COMMA_annot_pparamdecl__"
    | I.N I.N_loption_separated_nonempty_list_COMMA_annot_stor_type__ -> "loption_separated_nonempty_list_COMMA_annot_stor_type__"
    | I.N I.N_loption_separated_nonempty_list_COMMA_annotation__ -> "loption_separated_nonempty_list_COMMA_annotation__"
    | I.N I.N_loption_separated_nonempty_list_COMMA_pexpr__ -> "loption_separated_nonempty_list_COMMA_pexpr__"
    | I.N I.N_loption_separated_nonempty_list_COMMA_pexpr_noarr__ -> "loption_separated_nonempty_list_COMMA_pexpr_noarr__"
    | I.N I.N_loption_separated_nonempty_list_COMMA_range__ -> "loption_separated_nonempty_list_COMMA_range__"
    | I.N I.N_loption_separated_nonempty_list_COMMA_var__ -> "loption_separated_nonempty_list_COMMA_var__"
    | I.N I.N_module_ -> "module_"
    | I.N I.N_nonempty_list_prequire1_ -> "nonempty_list_prequire1_"
    | I.N I.N_option_COMMA_ -> "option_COMMA_"
    | I.N I.N_option_DOT_ -> "option_DOT_"
    | I.N I.N_option___anonymous_1_ -> "option___anonymous_1_"
    | I.N I.N_option_access_type_ -> "option_access_type_"
    | I.N I.N_option_arr_access_len_ -> "option_arr_access_len_"
    | I.N I.N_option_attribute_ -> "option_attribute_"
    | I.N I.N_option_call_conv_ -> "option_call_conv_"
    | I.N I.N_option_from_ -> "option_from_"
    | I.N I.N_option_loc_castop1__ -> "option_loc_castop1__"
    | I.N I.N_option_pblock_ -> "option_pblock_"
    | I.N I.N_option_pointer_ -> "option_pointer_"
    | I.N I.N_option_prefix_IF_pexpr__ -> "option_prefix_IF_pexpr__"
    | I.N I.N_option_prefix_RARROW_tuple_annot_stor_type___ -> "option_prefix_RARROW_tuple_annot_stor_type___"
    | I.N I.N_option_unaligned_ -> "option_unaligned_"
    | I.N I.N_option_writable_ -> "option_writable_"
    | I.N I.N_pblock -> "pblock"
    | I.N I.N_pblock_r -> "pblock_r"
    | I.N I.N_pelse -> "pelse"
    | I.N I.N_pelseif -> "pelseif"
    | I.N I.N_peqop -> "peqop"
    | I.N I.N_pexec -> "pexec"
    | I.N I.N_pexpr -> "pexpr"
    | I.N I.N_pexpr_noarr -> "pexpr_noarr"
    | I.N I.N_pexpr_noarr_r_pexpr_ -> "pexpr_noarr_r_pexpr_"
    | I.N I.N_pexpr_noarr_r_pexpr_noarr_ -> "pexpr_noarr_r_pexpr_noarr_"
    | I.N I.N_pexpr_r -> "pexpr_r"
    | I.N I.N_pfunbody -> "pfunbody"
    | I.N I.N_pfundef -> "pfundef"
    | I.N I.N_pgexpr -> "pgexpr"
    | I.N I.N_pglobal -> "pglobal"
    | I.N I.N_pif -> "pif"
    | I.N I.N_pinstr -> "pinstr"
    | I.N I.N_pinstr_r -> "pinstr_r"
    | I.N I.N_plvalue -> "plvalue"
    | I.N I.N_plvalue_r -> "plvalue_r"
    | I.N I.N_plvalues -> "plvalues"
    | I.N I.N_pointer -> "pointer"
    | I.N I.N_pparam -> "pparam"
    | I.N I.N_pparamdecl_empty_ -> "pparamdecl_empty_"
    | I.N I.N_prequire -> "prequire"
    | I.N I.N_prequire1 -> "prequire1"
    | I.N I.N_prim -> "prim"
    | I.N I.N_ptr -> "ptr"
    | I.N I.N_ptype -> "ptype"
    | I.N I.N_ptype_r -> "ptype_r"
    | I.N I.N_range -> "range"
    | I.N I.N_separated_nonempty_list_COLONCOLON_NID_ -> "separated_nonempty_list_COLONCOLON_NID_"
    | I.N I.N_separated_nonempty_list_COMMA_annot_pparamdecl_ -> "separated_nonempty_list_COMMA_annot_pparamdecl_"
    | I.N I.N_separated_nonempty_list_COMMA_annot_stor_type_ -> "separated_nonempty_list_COMMA_annot_stor_type_"
    | I.N I.N_separated_nonempty_list_COMMA_annotation_ -> "separated_nonempty_list_COMMA_annotation_"
    | I.N I.N_separated_nonempty_list_COMMA_loc_decl__ -> "separated_nonempty_list_COMMA_loc_decl__"
    | I.N I.N_separated_nonempty_list_COMMA_pexpr_ -> "separated_nonempty_list_COMMA_pexpr_"
    | I.N I.N_separated_nonempty_list_COMMA_pexpr_noarr_ -> "separated_nonempty_list_COMMA_pexpr_noarr_"
    | I.N I.N_separated_nonempty_list_COMMA_plvalue_ -> "separated_nonempty_list_COMMA_plvalue_"
    | I.N I.N_separated_nonempty_list_COMMA_range_ -> "separated_nonempty_list_COMMA_range_"
    | I.N I.N_separated_nonempty_list_COMMA_var_ -> "separated_nonempty_list_COMMA_var_"
    | I.N I.N_separated_nonempty_list_empty_var_ -> "separated_nonempty_list_empty_var_"
    | I.N I.N_separated_nonempty_list_option_COMMA__var_ -> "separated_nonempty_list_option_COMMA__var_"
    | I.N I.N_simple_attribute -> "simple_attribute"
    | I.N I.N_stor_type -> "stor_type"
    | I.N I.N_storage -> "storage"
    | I.N I.N_struct_annot -> "struct_annot"
    | I.N I.N_svsize -> "svsize"
    | I.N I.N_swsize -> "swsize"
    | I.N I.N_top -> "top"
    | I.N I.N_top_annotation -> "top_annotation"
    | I.N I.N_utype -> "utype"
    | I.N I.N_utype_array -> "utype_array"
    | I.N I.N_var -> "var"
    | I.N I.N_writable -> "writable"

  let pp_symbol : type a. a option -> Format.formatter -> a symbol -> unit =
    fun _ fmt s -> Format.pp_print_string fmt (name_of_symbol s)

  (* INSTR_ERROR_TOKEN is an error that only an instruction (or an item)
     accepts, ITEM_ERROR_TOKEN one that only an item accepts: Mastic folds
     the stack into it up to the instruction, or the item, which becomes an
     error. When Mastic merges errors it rebuilds the token from the merged
     Mastic.Error.t, so they are marked by a piece Lex "\001" or Lex "\000",
     which survives the merges. *)
  let item_marker = "\000"  (* not used *)
  let instr_marker = "\001"
  let has_marker m e = List.exists (fun x -> Mastic.Error.unloc x = Mastic.Error.Lex m) e
  let match_error_token = function
    | Parser.ERROR_TOKEN x | Parser.INSTR_ERROR_TOKEN x | Parser.ITEM_ERROR_TOKEN x -> Some x
    | _ -> None
  let build_error_token t =
    if has_marker item_marker t then Parser.ITEM_ERROR_TOKEN t
    else if has_marker instr_marker t then Parser.INSTR_ERROR_TOKEN t
    else Parser.ERROR_TOKEN t
  let is_eof_token = function Parser.EOF -> true | _ -> false

  (* the tokens the recovery may insert: the end of an instruction, and
     closing brackets *)
  let token_of_terminal : type a. a terminal -> (string * token) option =
    fun t -> if baseline then None else match t with
    | I.T_SEMICOLON -> Some (";", Parser.SEMICOLON)
    | I.T_RPAREN -> Some (")", Parser.RPAREN)
    | I.T_RBRACKET -> Some ("]", Parser.RBRACKET)
    | I.T_RBRACE -> Some ("}", Parser.RBRACE)
    | I.T_LBRACE -> Some ("{", Parser.LBRACE)
    | _ -> None

  (* -------------------------------------------------------------------- *)
  (* An item of the stack folded into an error keeps its content:
     expressions, types, left values, instructions and items become the
     error nodes of their type, the elements of lists are kept one by one,
     and anything else is kept as text *)

  let slice (b : Lexing.position) (e : Lexing.position) =
    let b = max 0 b.pos_cnum and e = min (String.length !text) e.pos_cnum in
    if e <= b then "" else String.sub !text b (e - b)
  let txt b e = Mastic.Error.(mkLexError (loc (slice b e) b e))

  let pos_of_loc (l : Location.t) =
    let p (line, col) n = { Lexing.pos_fname = l.loc_fname; pos_lnum = line; pos_bol = n - col; pos_cnum = n } in
    p l.loc_start l.loc_bchar, p l.loc_end l.loc_echar
  let located build x (l : Location.t) = let b, e = pos_of_loc l in build (Mastic.Error.loc x b e)
  let expr (x : pexpr) = located Expr.build_token x x.pl_loc
  let typ (x : ptype) = located Type.build_token x x.pl_loc
  let lvalue (x : plvalue) = located Lvalue.build_token x x.pl_loc
  let instr ((_, i) as x : pinstr) = located Instr.build_token x i.pl_loc
  let item (x : pitem Location.located) = located Item.build_token x.pl_desc x.pl_loc
  let all f l b e = match List.map f l with [] -> txt b e | x :: xs -> List.fold_left Mastic.Error.merge x xs
  (* the text, with the pieces of [l] inside it *)
  let with_text l b e = List.fold_left Mastic.Error.merge (txt b e) l

  let reduce_as_parse_error : type a. a -> a symbol -> Lexing.position -> Lexing.position -> token =
    fun x s b e ->
    let here build = build (Mastic.Error.loc x b e) in
    let wrap build v = build (Mastic.Error.loc (Location.mk_loc (Location.make b e) v) b e) in
    Parser.ERROR_TOKEN (match s with
    | I.N I.N_pexpr -> here Expr.build_token
    | I.N I.N_pexpr_noarr -> here Expr.build_token
    | I.N I.N_arr_access_len -> here Expr.build_token
    | I.N I.N_pexpr_r -> wrap Expr.build_token x
    | I.N I.N_pexpr_noarr_r_pexpr_ -> wrap Expr.build_token x
    | I.N I.N_pexpr_noarr_r_pexpr_noarr_ -> wrap Expr.build_token x
    | I.N I.N_option_prefix_IF_pexpr__ -> with_text (Option.to_list (Option.map expr x)) b e
    | I.N I.N_option_arr_access_len_ -> with_text (Option.to_list (Option.map expr x)) b e
    | I.N I.N_separated_nonempty_list_COMMA_pexpr_ -> all expr x b e
    | I.N I.N_separated_nonempty_list_COMMA_pexpr_noarr_ -> all expr x b e
    | I.N I.N_loption_separated_nonempty_list_COMMA_pexpr__ -> all expr x b e
    | I.N I.N_loption_separated_nonempty_list_COMMA_pexpr_noarr__ -> all expr x b e
    | I.N I.N_pgexpr -> (match x with GEexpr x -> expr x | GEarray l -> with_text (List.map expr l) b e)
    | I.N I.N_ptype -> here Type.build_token
    | I.N I.N_ptype_r -> wrap Type.build_token x
    | I.N I.N_stor_type -> with_text [typ (snd x)] b e
    | I.N I.N_annot_stor_type -> with_text [typ (snd (snd x))] b e
    | I.N I.N_plvalue -> here Lvalue.build_token
    | I.N I.N_plvalue_r -> wrap Lvalue.build_token x
    | I.N I.N_separated_nonempty_list_COMMA_plvalue_ -> all lvalue x b e
    | I.N I.N_plvalues -> with_text (List.map lvalue (snd x)) b e
    | I.N I.N_pinstr -> here Instr.build_token
    | I.N I.N_pinstr_r -> Instr.build_token (Mastic.Error.loc ([], Location.mk_loc (Location.make b e) x) b e)
    | I.N I.N_pif -> Instr.build_token (Mastic.Error.loc ([], Location.mk_loc (Location.make b e) x) b e)
    | I.N I.N_list_pinstr_ -> all instr x b e
    | I.N I.N_pblock_r -> all instr x b e
    | I.N I.N_pblock -> all instr x.pl_desc b e
    | I.N I.N_pelse -> all instr x.pl_desc b e
    | I.N I.N_option_pblock_ -> (match x with Some x -> all instr x.pl_desc b e | None -> txt b e)
    | I.N I.N_pfunbody -> with_text (List.map instr x.pdb_instr) b e
    | I.N I.N_top -> here Item.build_token
    | I.N I.N_list_loc_top__ -> all item x b e
    | _ -> txt b e)

  (* -------------------------------------------------------------------- *)
  (* the state of the parser *)

  let lhs_is f (lhs, _, _, _) = match lhs with I.X (I.N n) -> f (I.X (I.N n)) | _ -> false

  (* an item of an expression *)
  let is_expr = lhs_is (function
    | I.X (I.N (I.N_pexpr | I.N_pexpr_r | I.N_pexpr_noarr | I.N_pexpr_noarr_r_pexpr_
               | I.N_pexpr_noarr_r_pexpr_noarr_)) -> true
    | _ -> false)

  (* the state waits for an expression, a type or a left value: an item
     expects one next, and no item is complete *)
  (* the next symbol of an item, after the ones that can be empty (castop
     in x + y) *)
  let next (_, rhs, _, pos) =
    let rec skip = function
      | I.X (I.N n) :: rest when I.nullable n && rest <> [] -> skip rest
      | l -> l in
    List.nth_opt (skip (List.filteri (fun i _ -> i >= pos) rhs)) 0

  let expects_expr_or_type productions =
    List.for_all (fun i -> next i <> None) productions &&
    List.exists (fun i -> match next i with
      | Some (I.X (I.N (I.N_pexpr | I.N_pexpr_noarr | I.N_ptype | I.N_plvalue))) -> true
      | _ -> false) productions

  (* the beginning of an item: at the beginning of the file (the kernel item
     of the initial state), after an item, or after "namespace N {" *)
  let is_item_start (lhs, rhs, _, pos) =
    match lhs, pos with
    | I.X (I.N I.N_list_loc_top__), 1 -> true
    | I.X (I.N I.N_module_), 0 -> true
    | I.X (I.N I.N_top), 3 -> (match rhs with I.X (I.T I.T_NAMESPACE) :: _ -> true | _ -> false)
    | _ -> false

  (* the state waits for a block, or the body of a function *)
  let expects_block productions =
    List.exists (fun i -> match next i with
      | Some (I.X (I.N (I.N_pblock | I.N_pblock_r | I.N_pfunbody))) -> true
      | _ -> false) productions

  (* between two instructions of a block *)
  let is_instr_start (lhs, rhs, _, pos) =
    match lhs, pos with
    | I.X (I.N I.N_list_pinstr_), 1 -> true
    | I.X (I.N (I.N_pblock_r | I.N_pfunbody)), 1 -> true
    | _ -> false

  (* -------------------------------------------------------------------- *)
  (* restart points *)

  (* the token is the first of its line *)
  let first_on_line (p : Lexing.position) =
    let rec blank i = i >= p.pos_cnum || ((!text).[i] = ' ' || (!text).[i] = '\t') && blank (i + 1) in
    p.pos_cnum <= String.length !text && blank p.pos_bol

  (* the token probably begins the next item: a keyword that only begins
     items, or a token at the beginning of a line (column 0) *)
  let item_restart t (p : Lexing.position) =
    match t with
    | Parser.FN | Parser.PARAM | Parser.EXPORT | Parser.REQUIRE | Parser.FROM
    | Parser.NAMESPACE | Parser.EXEC | Parser.TYPE -> true
    | Parser.RBRACE | Parser.LBRACE -> false
    | _ -> p.pos_cnum = p.pos_bol

  (* the token probably begins the next instruction: a keyword that only
     begins instructions, or the first token of a line *)
  let instr_restart t (p : Lexing.position) =
    match t with
    | Parser.IF | Parser.FOR | Parser.WHILE | Parser.ARRAYINIT | Parser.ASSERT | Parser.RETURN -> true
    | Parser.RBRACE | Parser.LBRACE | Parser.ELSE -> false
    | _ -> first_on_line p

  (* -------------------------------------------------------------------- *)

  let handle_unexpected_token ~productions ~next_token ~acceptable_tokens
      ~reducible_productions ~generation_streak =
    let open Mastic.ErrorResilientParser in
    let accept l = List.find_map (fun t -> List.find_opt (fun x -> x.t = t) acceptable_tokens) l in
    let marked m t s =
      let b = next_token.b in
      GenerateToken { s; b; e = b; t = t Mastic.Error.(mkLexError (loc m b b)) } in
    let lbrace () = GenerateToken { s = "{"; t = Parser.LBRACE; b = next_token.b; e = next_token.b } in
    let instr_error () = marked instr_marker (fun x -> Parser.INSTR_ERROR_TOKEN x) "(error)" in
    (* between two instructions of a block, or two items of a namespace *)
    let in_block = List.exists (fun i -> is_instr_start i || is_item_start i) productions in
    (* finish the current item (at the end of the file, or at a token that
       begins an item): reduce if possible, otherwise insert the ";" or a
       bracket if it fits, between two instructions close the block, then
       try a hole for a missing expression, and finally make the current
       instruction an error (or the item, outside a function) *)
    let finish_item () =
      match reducible_productions with
      | p :: _ -> Reduce p
      | [] ->
      match accept Parser.[SEMICOLON; RPAREN; RBRACKET; RBRACE; LBRACE] with
      | Some x -> GenerateToken x
      | None ->
          if expects_block productions then lbrace ()
          else if in_block then GenerateToken { s = "}"; t = Parser.RBRACE; b = next_token.b; e = next_token.b }
          else if generation_streak <= 1 then GenerateHole
          else instr_error () in
    (* finish the current instruction (at a token that begins an
       instruction): the same, without closing the block, and inserting
       the ";" anyway (Menhir may accept it after reductions of empty rules,
       that Mastic does not list) *)
    let finish_instr () =
      match reducible_productions with
      | p :: _ -> Reduce p
      | [] ->
      match accept Parser.[SEMICOLON; RPAREN; RBRACKET] with
      | Some x -> GenerateToken x
      | None ->
          if expects_block productions then lbrace ()
          else if next_token.t <> Parser.SEMICOLON && generation_streak <= 1 then
            GenerateToken { s = ";"; t = Parser.SEMICOLON; b = next_token.b; e = next_token.b }
          else if generation_streak <= 2 then GenerateHole
          else instr_error () in
    if baseline then
      match reducible_productions with
      | p :: _ when List.exists is_expr productions -> Reduce p
      | _ -> TurnIntoError
    else
    if generation_streak >= 10 then TurnIntoError
    else if List.exists is_item_start productions && next_token.t <> Parser.EOF then TurnIntoError
    else if reducible_productions = [] && generation_streak = 0 && expects_expr_or_type productions then
      (* an expression (or a type, a left value) is missing: an error node
         takes its place, as in x = a + ; read x = a + Err; *)
      GenerateHole
    else match next_token.t with
    | Parser.EOF -> finish_item ()
    | t when item_restart t next_token.b -> finish_item ()
    | t when instr_restart t next_token.b -> finish_instr ()
    | Parser.RBRACE -> finish_instr ()
    | Parser.LBRACE when generation_streak = 0 ->
        (* a block that does not fit: what is before it is broken, a hole
           folds it into an error, after which the block may fit (as the
           body of a function whose header is broken, for instance) *)
        GenerateHole
    | _ ->
    match reducible_productions with
    | p :: _ when List.exists is_expr productions -> Reduce p
    | _ -> TurnIntoError
end

module ErProgram = Mastic.ErrorResilientParser.Make (I) (ProgramParser) (Recovery)

let () = Mastic.ErrorResilientParser.debug := Sys.getenv_opt "MASTIC_DEBUG" <> None

(* consecutive error items, and consecutive error instructions, are merged *)
let rec merge_items = function
  | { Location.pl_desc = PError x; pl_loc = l } :: { Location.pl_desc = PError y; pl_loc = l' } :: rest ->
      merge_items ({ Location.pl_desc = PError (Mastic.Error.merge x y); pl_loc = Location.merge l l' } :: rest)
  | ({ Location.pl_desc = PFundef f; _ } as d) :: rest ->
      { d with pl_desc = PFundef { f with pdf_body = { f.pdf_body with pdb_instr = merge_instrs f.pdf_body.pdb_instr } } }
      :: merge_items rest
  | ({ Location.pl_desc = PFunError (e, b); _ } as d) :: rest ->
      { d with pl_desc = PFunError (e, { b with pdb_instr = merge_instrs b.pdb_instr }) } :: merge_items rest
  | ({ Location.pl_desc = PNamespace (n, l); _ } as d) :: rest ->
      { d with pl_desc = PNamespace (n, merge_items l) } :: merge_items rest
  | d :: rest -> d :: merge_items rest
  | [] -> []

and merge_instrs = function
  | (a, ({ Location.pl_desc = PIError x; _ } as i)) :: (_, { Location.pl_desc = PIError y; pl_loc = l' }) :: rest ->
      merge_instrs ((a, { Location.pl_desc = PIError (Mastic.Error.merge x y); pl_loc = Location.merge i.pl_loc l' }) :: rest)
  | (a, i) :: rest -> (a, { i with pl_desc = merge_instr i.pl_desc }) :: merge_instrs rest
  | [] -> []

and merge_block (b : pblock) = { b with pl_desc = merge_instrs b.pl_desc }

and merge_instr = function
  | PIIf (c, b1, b2) -> PIIf (c, merge_block b1, Option.map merge_block b2)
  | PIFor (v, r, b) -> PIFor (v, r, merge_block b)
  | PIWhile (b1, c, b2) -> PIWhile (Option.map merge_block b1, c, Option.map merge_block b2)
  | PIErrorBlock (e, b) -> PIErrorBlock (e, merge_block b)
  | i -> i

(* One resilient parse: the lexer returns error tokens instead of raising;
   its errors are added to the ones of Mastic, one per position. *)
let resilient lexbuf =
  text := Bytes.sub_string lexbuf.Lexing.lex_buffer 0 lexbuf.Lexing.lex_buffer_len;
  let saved = !Lexer.recovering, !Lexer.errors in
  Lexer.recovering := not baseline; Lexer.errors := [];
  let errs, comps, ast = Fun.protect ~finally:(fun () -> Lexer.recovering := fst saved; Lexer.errors := snd saved)
    (fun () ->
      let errs, comps, ast = ErProgram.parse lexbuf in
      let lex = List.map (fun (p, m) -> Mastic.ErrorResilientParser.LexError (p, m)) !Lexer.errors in
      lex @ errs, comps, ast) in
  (* the errors, in the order of the text *)
  let pos = function Mastic.ErrorResilientParser.LexError (p, _) | ParseError (p, _) -> p.Lexing.pos_cnum in
  let errs = List.stable_sort (fun x y -> compare (pos y) (pos x)) errs in
  let rec dedup = function
    | x :: (y :: _ as rest) when pos x = pos y -> dedup (x :: List.tl rest)
    | x :: rest -> x :: dedup rest
    | [] -> [] in
  dedup (List.rev errs), comps, merge_items ast
